ConstructionProjectManagement/ConstructionProjectManagement/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [

    path('admin/', admin.site.urls),
    path('accounts/', include('accounts.urls')),
    path('', include('common.urls')),
    path('projects/', include('projects.urls')),

    path('builders/', include('builders.urls')),

    path('designers/', include('designers.urls')),
    path('supervisions/', include('supervisions.urls')),
    path('tasks/', include('tasks.urls')),
]

if settings.DEBUG:
    # urlpatterns += static(settings.STATIC_URL, document_root=settings.STATICFILES_DIRS[0])
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

ConstructionProjectManagement/projects/urls.py
from django.urls.conf import path, include

from projects import views

urlpatterns = [
    path('', views.ProjectPageView.as_view(), name='projects'),
    path('create/', views.CreateProjectView.as_view(), name='project-create'),
    path('<int:pro_pk>/', include([
        path('details/', views.DetailsProjectView.as_view(), name='project-details'),
        path('edit/', views.EditProjectView.as_view(), name='project-edit'),
        path('delete/', views.DeleteProjectView.as_view(), name='project-delete'),
    ]))

]

ConstructionProjectManagement/tasks/urls.py
from django.urls.conf import path, include

from tasks import views

urlpatterns = [
    path('', views.TaskListView.as_view(), name='tasks'),
    path('create/', views.TaskCreateView.as_view(), name='task-create'),
    path('<int:pk>/', include([
        path('detail/', views.TaskDetailView.as_view(), name='task-detail'),
        path('edit/', views.TaskEditView.as_view(), name='task-edit'),
        path('delete/', views.TaskDeleteView.as_view(), name='task-delete'),
    ])),
    # path('reports/', views.ReportListView.as_view(), name='reports'),
    path('report-add/', views.ReportCreateView.as_view(), name='report-add'),
    path('report/<int:rep_pk>/', include([
        path('detail/', views.ReportDetailView.as_view(), name='report-detail'),
        path('edit/', views.ReportEditView.as_view(), name='report-edit'),
        path('delete/', views.ReportDeleteView.as_view(), name='report-delete'),
    ]))

]

ConstructionProjectManagement/projects/models.py
from django.contrib.auth import get_user_model
from django.db import models
from projects.choices import DevelopmentChoices
from django.core.validators import MaxValueValidator, MinValueValidator, MinLengthValidator

UserModel = get_user_model()


# Create your models here.
class Project(models.Model):
    title = models.CharField(max_length=300)
    code_project = models.CharField(max_length=10, validators=[MinLengthValidator(5)], default=00000)
    content = models.TextField()
    coordinator = models.CharField(max_length=30)
    investor = models.CharField(max_length=30)
    date_start = models.DateField(blank=True, null=True)
    development = models.CharField(max_length=50, choices=DevelopmentChoices.choices)
    user = models.ForeignKey(
        UserModel,
        on_delete=models.CASCADE, related_name='created_by'
    )

    def __str__(self):
        return self.title

ConstructionProjectManagement/projects/forms.py
from django import forms

from core.mixins import ReadOnlyFieldsMixin
from projects.choices import DevelopmentChoices
from projects.models import Project


class ProjectBaseForm(forms.ModelForm):
    class Meta:
        model = Project
        exclude = ('user',)
        labels = {
            'title': 'Project name:',
            'code_project': 'Code project:',
            'content': 'Description:',
            'coordinator': 'Coordinator:',
            'investor': 'Investor control:',
            'date_start': 'Start project:',
            'development': 'Development Status:',
        }
        widgets = {
            'title': forms.TextInput(attrs={'placeholder': 'Enter project name'}),
            'code_project': forms.TextInput(attrs={'placeholder': 'Enter code project'}),
            'content': forms.Textarea(attrs={'placeholder': 'Enter description'}),
            'coordinator': forms.TextInput(attrs={'placeholder': 'Enter coordinator'}),
            'investor': forms.TextInput(attrs={'placeholder': 'Enter investor control'}),
            'date_start': forms.DateInput(attrs={'type': 'date'}),
            'development': forms.Select(),
        }


class ProjectCreateForm(ProjectBaseForm):
    ...


class ProjectEditForm(ProjectBaseForm):
    ...


class ProjectDetailsForm(ProjectBaseForm):
    ...


class ProjectDeleteForm(ProjectBaseForm, ReadOnlyFieldsMixin):
    class Meta:
        model = Project
        exclude = ('coordinator', 'investor', 'user')

ConstructionProjectManagement/projects/views.py
from django.contrib.auth.mixins import LoginRequiredMixin, PermissionRequiredMixin
from django.urls.base import reverse_lazy, reverse
from django.views.generic import CreateView
from django.views.generic.detail import DetailView
from django.views.generic.edit import UpdateView, DeleteView
from django.views.generic.list import ListView

from projects.forms import ProjectCreateForm, ProjectEditForm, ProjectDeleteForm, ProjectDetailsForm
from projects.models import Project


# Create your views here.


class ProjectPageView(ListView):
    model = Project
    template_name = 'projects/projects-page.html'


class CreateProjectView(PermissionRequiredMixin, CreateView):
    permission_required = 'projects.add_project'
    model = Project
    template_name = 'projects/projects-create.html'
    form_class = ProjectCreateForm

    def form_valid(self, form):
        self.object = form.save(commit=False)
        self.object.user = self.request.user
        self.object.save()
        return super().form_valid(form)

    def get_success_url(self) -> str:
        return reverse(
            'projects',
        )


class DetailsProjectView(LoginRequiredMixin, DetailView):
    model = Project
    template_name = 'projects/projects-details.html'
    pk_url_kwarg = 'pro_pk'

    def get_context_data(self, **kwargs):
        project = self.get_object()
        total_sum_designers = sum([designer.budged for designer in project.designers.all()]) or 0
        total_sum_builders = sum([build.budged for build in project.builders.all()]) or 0
        total_sum_supervisions = sum([supervision.budged for supervision in project.supervisions.all()]) or 0
        total_budget_project = total_sum_designers + total_sum_builders + total_sum_supervisions

        kwargs.update({
            "total_budget_project": total_budget_project,
            "project": project,
        })
        return super().get_context_data(**kwargs)


class EditProjectView(PermissionRequiredMixin, UpdateView):
    permission_required = 'projects.change_project'
    model = Project
    form_class = ProjectEditForm
    template_name = 'projects/projects-edit.html'
    pk_url_kwarg = 'pro_pk'

    def get_success_url(self) -> str:
        return reverse(
            'project-details', kwargs={'pro_pk': self.object.pk}
        )


class DeleteProjectView(PermissionRequiredMixin, DeleteView):
    permission_required = 'projects.delete_project'
    model = Project
    form_class = ProjectDeleteForm
    template_name = 'projects/projects-delete.html'
    pk_url_kwarg = 'pro_pk'
    success_url = reverse_lazy('projects')

    def get_initial(self) -> dict:
        return self.object.__dict__

    def get_form_kwargs(self):
        kwargs = super().get_form_kwargs()
        kwargs.update({"data": self.get_initial()})
        return kwargs

ConstructionProjectManagement/templates/projects/projects-create.html
{% extends 'base.html'%}
{% load static %}
{% block content %}
        <main>
                <article class="top">
                     <div class="register-form form">
                         <h2 class="project-details">Create Project</h2>
                        <form class="" method="POST" action="{% url 'project-create' %}">
                            {% csrf_token %}
                            {{ form }}
                            <div class="button">
                                <button type="submit">Create</button>
                            </div>
                        </form>
                     </div>
                </article>
        </main>
{% endblock %}

ConstructionProjectManagement/templates/projects/projects-delete.html
{% extends 'base.html' %}
{% load static %}
{% block content %}
        <main>
                <article class="top">
                     <div class="register-form form">
                        <form class="" method="POST" action="{% url 'project-delete' pro_pk=project.pk %}">
                            {% csrf_token %}
                            {{ form }}
                            <p> Are you sure so want to delete project?</p>
                            <div class="button">
                                <button type="submit">Delete</button>
                            </div>
                        </form>   
                     </div>
                </article>
        </main>
{% endblock %}

ConstructionProjectManagement/templates/projects/projects-details.html
{% extends 'base.html' %}
{% load static %}
{% block content %}
        <main>
                <article class="top">
                    <div class="register-form form">
                        <form class="" method="GET" action="">
                            <h2 class="project-details">Project details</h2>
                            <h3 class="details-head">Project name:</h3>
                            <div class="context">{{ project.title }}</div>
                            <h3 class="project-head">Code project:</h3>
                            <div class="context">{{ project.code_project }}</div>
                            <h3 class="project-head">Description:</h3>
                            <div class="context">{{ project.content }}</div>
                            <h3 class="project-head">Coordinator:</h3>
                            <div class="context">{{ project.coordinator }}</div>
                            <h3 class="project-head">Investor control:</h3>
                            <div class="context">{{ project.investor }}</div>
                            <h3 class="project-head">Start project:</h3>
                            <div class="context">{{ project.date_start|date:'d-m-Y' }}</div>
                            <h3 class="project-head">Development:</h3>
                            <div class="context">{{ project.development }}</div>
                            <div class="button">
                                <button><a href="{% url 'project-edit' pro_pk=project.pk %}">Edit</a></button>
                                <button><a href="{% url 'project-delete' pro_pk=project.pk %}">Delete</a></button>
                            </div>
                        </form>
                        <h3 class="project-head">Budget:</h3>
                        <div class="context">{{total_budget_project|default:0}}</div>
                        <a href="{% url 'builders' %}" class="see-more project-head"><h3>Builders</h3></a>
                        <a href="{% url 'designers' %}" class="see-more project-head"><h3>Designers</h3></a>
                        <a href="{% url 'supervisions' %}" class="see-more project-head"><h3>Supervisions</h3></a>
                        <a href="{% url 'tasks' %}" class="see-more project-head"><h3>Tasks</h3></a>
                     </div>
                </article>
        </main>
{% endblock %}

ConstructionProjectManagement/templates/projects/projects-edit.html
{% extends 'base.html' %}
{% load static %}
{% block content %}
        <main>
                <article class="top">
                    <div class="register-form form">
                        <h2 class="project-details">Edit Project</h2>
                        <form class="" method="POST" action="{% url 'project-edit' pro_pk=project.pk %}">
                            {% csrf_token %}
                            {{ form }}
                            <div class="button">
                                <button type="submit">Edit</button>
                            </div>
                        </form>
                        <a href="{% url 'builders' %}" class="see-more project-head"><h3>Edit Builders</h3></a>
                        <div class="context">{{ project.builders.all|join:', ' |default:'N/A'}}</div>
                        <a href="{% url 'designers' %}" class="see-more project-head"><h3>Edit Designers</h3></a>
                        <div class="context">{{ project.designers.all|join:', ' |default:'N/A' }}</div>
                        <a href="{% url 'supervisions' %}" class="see-more project-head"><h3>Edit Supervisions</h3></a>
                        <div class="context">{{ project.supervisions.all|join:', ' |default:'N/A' }}</div>
                    </div>
                </article>
        </main>
{% endblock %}

ConstructionProjectManagement/templates/projects/projects-page.html
{% extends 'base.html' %}
{% load static %}
{% block content %}
        <main>
            <section class="project-all">
                {% for project in project_list %}
                    <article class="top">
                            <div class="register-form form">
                                <h2 class="project-details">Project {{ project.code_project }}</h2>
                                <h3 class="project-head">Project name</h3>
                                <div class="context">{{ project.title }}</div>
                                <h3 class="project-head">Description</h3>
                                <div class="context">{{ project.content }}</div>
                                <h3 class="project-head">Builder</h3>
                                <div class="context">{{ project.builders.all|join:', ' |default:'N/A' }}</div>
                                <h3 class="project-head">Designer</h3>
                                <div class="context">{{ project.designers.all|join:', ' |default:'N/A' }}</div>
                                <h3 class="project-head">Supervision</h3>
                                <div class="context">{{ project.supervisions.all|join:', ' |default:'N/A' }}</div>
                                <a href="{% url 'project-details' pro_pk=project.pk %}" class="see-more">See more</a>
                            </div>
                    </article>
                {% empty %}
                <h3>No projects added</h3>
                {% endfor %}
            </section>
        </main>
{% endblock %}