ConstructionProjectManagement/ConstructionProjectManagement/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [

    path('admin/', admin.site.urls),
    path('accounts/', include('accounts.urls')),
    path('', include('common.urls')),
    path('projects/', include('projects.urls')),

    path('builders/', include('builders.urls')),

    path('designers/', include('designers.urls')),
    path('supervisions/', include('supervisions.urls')),
    path('tasks/', include('tasks.urls')),
]

if settings.DEBUG:
    # urlpatterns += static(settings.STATIC_URL, document_root=settings.STATICFILES_DIRS[0])
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

ConstructionProjectManagement/tasks/urls.py
from django.urls.conf import path, include

from tasks import views

urlpatterns = [
    path('', views.TaskListView.as_view(), name='tasks'),
    path('create/', views.TaskCreateView.as_view(), name='task-create'),
    path('<int:pk>/', include([
        path('detail/', views.TaskDetailView.as_view(), name='task-detail'),
        path('edit/', views.TaskEditView.as_view(), name='task-edit'),
        path('delete/', views.TaskDeleteView.as_view(), name='task-delete'),
    ])),
    # path('reports/', views.ReportListView.as_view(), name='reports'),
    path('report-add/', views.ReportCreateView.as_view(), name='report-add'),
    path('report/<int:rep_pk>/', include([
        path('detail/', views.ReportDetailView.as_view(), name='report-detail'),
        path('edit/', views.ReportEditView.as_view(), name='report-edit'),
        path('delete/', views.ReportDeleteView.as_view(), name='report-delete'),
    ]))

]

ConstructionProjectManagement/tasks/models.py
from django.contrib.auth import get_user_model
from django.db import models
from projects.models import Project


# Create your models here.

UserModel = get_user_model()


class Task(models.Model):
    description = models.TextField()
    author = models.ForeignKey(
        UserModel,
        on_delete=models.CASCADE,
    )
    date_approved = models.DateTimeField(auto_now_add=True)
    project = models.ForeignKey(Project, on_delete=models.CASCADE, related_name='tasks')

    def __str__(self):
        return self.project.title


class Report(models.Model):
    answer = models.TextField()
    date_report = models.DateTimeField(auto_now=True)
    reporter = models.ForeignKey(
        UserModel,
        on_delete=models.CASCADE,
    )
    task = models.ForeignKey(Task, on_delete=models.CASCADE, related_name='reports')

ConstructionProjectManagement/tasks/forms.py
from django import forms
from core.mixins import TaskBaseForm, ReadOnlyFieldsMixin, ReportBaseForm
from projects.models import Project
from tasks.models import Task, UserModel, Report


# Forms for Tasks
class TaskMainForm(TaskBaseForm):
    project = forms.ModelChoiceField(
        queryset=Project.objects.all(),
        required=False,
        label="Connect to projects",
        widget=forms.Select()
    )

    # author = forms.ModelChoiceField(
    #     queryset=UserModel.objects.all(),
    #     required=False,
    #     label="Author",
    #     widget=forms.Select()
    # )

    class Meta(TaskBaseForm.Meta):
        model = Task
        # fields = '__all__'
        exclude = ('author',)


class TaskCreateForm(TaskMainForm):
    ...


class TaskEditForm(TaskMainForm):
    ...


class TaskDetailForm(TaskMainForm):
    ...


class TaskDeleteForm(TaskMainForm, ReadOnlyFieldsMixin):
    class Meta(TaskMainForm.Meta):
        model = Task
        exclude = ('project', 'author')


# Forms for report
class ReportMainForm(ReportBaseForm):
    task = forms.ModelChoiceField(
        queryset=Task.objects.all(),
        required=False,
        label="Connect to tasks",
        widget=forms.Select()
    )
    # reporter = forms.ModelChoiceField(
    #     queryset=UserModel.objects.all(),
    #     required=False,
    #     label="Reporter",
    #     widget=forms.Select()
    # )

    class Meta(ReportBaseForm.Meta):
        model = Report
        exclude = ('reporter',)


class ReportCreateForm(ReportMainForm):
    ...


class ReportEditForm(ReportMainForm):
    ...


class ReportDetailForm(ReportMainForm):
    ...


class ReportDeleteForm(ReportMainForm, ReadOnlyFieldsMixin):
    class Meta(ReportMainForm.Meta):
        model = Report
        exclude = ('task', 'reporter',)

ConstructionProjectManagement/tasks/views.py
from django.contrib.auth.mixins import LoginRequiredMixin, PermissionRequiredMixin
from django.core.exceptions import PermissionDenied
from django.urls.base import reverse, reverse_lazy
from django.views.generic.detail import DetailView
from django.views.generic.edit import CreateView, UpdateView, DeleteView
from django.views.generic.list import ListView

from tasks.forms import TaskCreateForm, ReportCreateForm, ReportEditForm, TaskEditForm, TaskDeleteForm, ReportDeleteForm
from tasks.models import Task, Report


# Create your views here.
# Views for Tasks
class TaskListView(PermissionRequiredMixin, ListView):
    permission_required = 'tasks.view_task'
    model = Task
    template_name = 'tasks/tasks.html'


class TaskCreateView(PermissionRequiredMixin, CreateView):
    permission_required = 'tasks.add_task'
    model = Task
    template_name = 'tasks/tasks-create.html'
    form_class = TaskCreateForm

    def form_valid(self, form):
        self.object = form.save(commit=False)
        self.object.author = self.request.user
        self.object.save()
        return super().form_valid(form)

    def get_success_url(self):
        return reverse('tasks')


class TaskDetailView(PermissionRequiredMixin, DetailView):
    permission_required = 'tasks.view_task'
    model = Task
    template_name = 'tasks/tasks-details.html'
    pk_url_kwarg = 'pk'

    def get_context_data(self, **kwargs):
        task = self.get_object()
        kwargs.update({'task': task})
        return super().get_context_data(**kwargs)


class TaskEditView(PermissionRequiredMixin, UpdateView):
    permission_required = 'tasks.change_task'
    model = Task
    template_name = 'tasks/tasks-edit.html'
    pk_url_kwarg = 'pk'
    form_class = TaskEditForm

    def get_success_url(self):
        return reverse('task-detail', kwargs={'pk': self.object.pk})


class TaskDeleteView(PermissionRequiredMixin, DeleteView):
    permission_required = 'tasks.delete_task'
    model = Task
    template_name = 'tasks/tasks-delete.html'
    pk_url_kwarg = 'pk'
    form_class = TaskDeleteForm
    success_url = reverse_lazy('tasks')

    def get_initial(self) -> dict:
        return self.object.__dict__

    def get_form_kwargs(self):
        kwargs = super().get_form_kwargs()
        kwargs.update({"data": self.get_initial()})
        return kwargs


# Views for Reports
# class ReportListView(ListView):
#     model = Report
#     template_name = 'tasks/reports.html'


# class ReportCreateView(LoginRequiredMixin, CreateView):
#     model = Report
#     template_name = 'tasks/report-create.html'
#     form_class = ReportCreateForm
#
#     def form_valid(self, form):
#         self.object = form.save(commit=False)
#         self.object.reporter = self.request.user
#         self.object.save()
#         return super().form_valid(form)
#
#     def get_success_url(self):
#         return reverse('tasks')
class ReportCreateView(PermissionRequiredMixin, CreateView):
    permission_required = 'tasks.add_report'
    model = Report
    template_name = 'tasks/report-create.html'
    form_class = ReportCreateForm

    def form_valid(self, form):
        self.object = form.save(commit=False)
        self.object.reporter = self.request.user
        task_id = self.request.GET.get('task_id')
        if task_id:
            from tasks.models import Task
            try:
                task = Task.objects.get(pk=task_id)
                self.object.task = task
            except Task.DoesNotExist:
                pass
        self.object.save()
        return super().form_valid(form)

    def get_success_url(self):
        return reverse('task-detail', kwargs={'pk': self.object.task.pk})


class ReportDetailView(PermissionRequiredMixin, DetailView):
    permission_required = 'tasks.view_report'
    model = Report
    template_name = 'tasks/report-detail.html'
    pk_url_kwarg = 'rep_pk'

    def get_context_data(self, **kwargs):
        report = self.get_object()
        kwargs.update({'report': report})
        return super().get_context_data(**kwargs)


class ReportEditView(PermissionRequiredMixin, UpdateView):
    permission_required = 'tasks.change_report'
    model = Report
    template_name = 'tasks/report-edit.html'
    pk_url_kwarg = 'rep_pk'
    form_class = ReportEditForm

    def form_valid(self, form):
        self.object = form.save(commit=False)
        if self.object.reporter == self.request.user:
            self.object.save()
            return super().form_valid(form)
        else:
            raise PermissionDenied

    def get_success_url(self):
        return reverse('report-detail', kwargs={'rep_pk': self.object.pk})


class ReportDeleteView(PermissionRequiredMixin, DeleteView):
    permission_required = 'tasks.delete_report'
    model = Report
    template_name = 'tasks/report-delete.html'
    pk_url_kwarg = 'rep_pk'
    form_class = ReportDeleteForm

    def get_initial(self) -> dict:
        return self.object.__dict__

    def get_form_kwargs(self):
        kwargs = super().get_form_kwargs()
        kwargs.update({"data": self.get_initial()})
        return kwargs

    def get_success_url(self):
        return reverse('task-detail', kwargs={'pk': self.object.task.pk})

ConstructionProjectManagement/templates/tasks/report-create.html
{% extends 'base.html' %}
{% load static %}
{% block content %}
        <main>
                <article class="top">
                     <div class="register-form form">
                        <form class="" method="POST" action="{% url 'report-add' %}">
                            <h3 class="project-head">Create Report</h3>
                            {% csrf_token %}
                            {{ form }}
{#                            <div class="context">#}
{#                                <p class="content-p">This is report hkhkkkhkhhkhk oioiuouou[09klj poiupoioiikjk</p>#}
{#                                <p class="author">Reporter: Ivan Ivanov Position: Technical manager</p>#}
{#                                <p class="author">Company: Stroitel AD Reported at 22.2.2024 15:30</p>#}
{#                            </div>#}
                            <div class="button">
                               <button type="submit">Create</button>
                            </div>
                        </form>
                     </div>
                </article>
        </main>
{% endblock %}

ConstructionProjectManagement/templates/tasks/report-delete.html
{% extends 'base.html' %}
{% load static %}
{% block content %}
        <main>
                <article class="top">
                     <div class="register-form form">
                        <form class="" method="POST" action="{% url 'report-delete' rep_pk=report.pk %}">
                            <h3 class="project-head">Delete Report</h3>
                            {% csrf_token %}
                            {{ form }}
                            <div class="button">
                               <button type="submit">Delete</button>
                            </div>
                        </form>
                     </div>
                </article>
        </main>
{% endblock %}

ConstructionProjectManagement/templates/tasks/report-detail.html
{% extends 'base.html' %}
{% load static %}
{% block content %}
        <main>
                <article class="top">
                     <div class="register-form form">
                        <form class="" method="GET" action="">
                            <h3 class="project-head">Report detail</h3>
                            <div class="context">
                                <p class="content-p">{{ report.answer }}</p>
                                <p class="author">Reporter: {{ report.reporter.profile.profiles_name }} Position: {{ report.reporter.profile.position }}</p>
                                <p class="author">Company: {{ report.reporter.profile.company_job }} Reported at {{ report.date_report|date:'d-m-Y' }}</p>
                                <div class="report-a">
                                    <a href="{% url 'report-edit' rep_pk=report.pk %}"><i class="fa-regular fa-pen-to-square"></i></a>
                                    <a href="{% url 'report-delete' rep_pk=report.pk %}"><i class="fa-regular fa-trash-can"></i></a>
                               </div>
                            </div>
                        </form>
                     </div>
                </article>
        </main>
{% endblock %}

ConstructionProjectManagement/templates/tasks/report-edit.html
{% extends 'base.html' %}
{% load static %}
{% block content %}
        <main>
                <article class="top">
                     <div class="register-form form">
                        <form class="" method="POST" action="{% url 'report-edit' rep_pk=report.pk %}">
                            <h3 class="project-head">Edit Report</h3>
                            {% csrf_token %}
                            {{ form }}
{#                            <div class="context">#}
{#                                <p class="content-p">This is report hkhkkkhkhhkhk oioiuouou[09klj poiupoioiikjk</p>#}
{#                                <p class="author">Reporter: Ivan Ivanov Position: Technical manager</p>#}
{#                                <p class="author">Company: Stroitel AD Reported at 22.2.2024 15:30</p>#}
{#                            </div>#}
                            <div class="button">
                               <button type="submit">Edit</button>
                            </div>
                        </form>
                     </div>
                </article>
        </main>
{% endblock %}

ConstructionProjectManagement/templates/tasks/reports.html
{% extends 'base.html' %}
{% load static %}
{% block content %}
        <main>
                <article class="top">
                     <div class="register-form form">
                        <h2 class="project-details">Reports</h2>
                         {% for report in report_list %}
                        <ul class="list">
                           <li>
                               <a href="{% url 'report-detail' rep_pk=report.pk %}" class="see-more">Reporter{{ report.reporter.profile.profiles_name }}</a>
                           </li>
                        </ul>
                         {% empty %}
                        <div class="project-head"><h3>No Reports added</h3></div>
                         {% endfor %}
                        <div class="button">
                           <button><a href="{% url 'report-add' %}">Add</a></button>
                        </div>
                     </div>
                </article>
        </main>
{% endblock %}

ConstructionProjectManagement/templates/tasks/tasks-create.html
{% extends 'base.html' %}
{% load static %}
{% block content %}
        <main>
                <article class="top">
                    <div class="register-form form">
                       <h2 class="project-details">Create Task</h2>
                       <form class="" method="POST" action="{% url 'task-create' %}">
                           {% csrf_token %}
                           {{ form }}
{#                            <div class="context">#}
{#                                <p class="content-p">Gazoprovod Europ Africakjkjhkjkhk jhhhhhhhhh </p>#}
{#                                <p class="author">Author: Ivan Ivanov Position: Technical manager</p>#}
{#                                <p class="author">Company: Stroitel AD Created at 22.2.2024 15:30</p>#}
{#                            </div>#}
                            <div class="button">
                                <button type="submit">Create</button>
                            </div>
                       </form>
                    </div>
                </article>
        </main>
{% endblock %}

ConstructionProjectManagement/templates/tasks/tasks-delete.html
{% extends 'base.html' %}
{% load static %}
{% block content %}
        <main>
                <article class="top">
                    <div class="register-form form">
                       <h2 class="project-details">Delete Task</h2>
                       <form class="" method="POST" action="{% url 'task-delete' pk=task.pk %}">
                           {% csrf_token %}
                           {{ form }}
{#                            <div class="context">#}
{#                                <p class="content-p">Gazoprovod Europ Africakjkjhkjkhk jhhhhhhhhh </p>#}
{#                                <p class="author">Author: Ivan Ivanov Position: Technical manager</p>#}
{#                                <p class="author">Company: Stroitel AD Created at 22.2.2024 15:30</p>#}
{#                            </div>#}
                            <div class="button">
                                <button type="submit">Delete</button>
                            </div>
                       </form>
                    </div>
                </article>
        </main>
{% endblock %}

ConstructionProjectManagement/templates/tasks/tasks-details.html
{% extends 'base.html' %}
{% load static %}
{% block content %}
        <main>
                <article class="top">
                     <div class="register-form form">
                        <h2 class="project-details">Tasks and report</h2>
                        <!-- <form class="" method="" action=""> -->
                        <h3 class="project-head">Task {{ task.project.title }}</h3>
                        <div class="context">
                            <p class="content-p">{{ task.description }}</p>
                            <p class="author">Author: {{ task.author.profile.profiles_name }} Position: {{ task.author.profile.position }}</p>
                            <p class="author">Company: {{ task.author.profile.company_job }} Reported at {{ task.date_approved|date:'d-m-Y' }}</p>
                            <div class="report-a">
                                <a href="{% url 'task-edit' pk=task.pk %}"><i class="fa-regular fa-pen-to-square"></i></a>
                                <a href="{% url 'task-delete' pk=task.pk %}"><i class="fa-regular fa-trash-can"></i></a>
                            </div>
                        </div>
                                <h3 class="project-details">Reports</h3>
                                 {% for report in task.reports.all %}
                                <ul class="list">
                                   <li>
                                       <a href="{% url 'report-detail' rep_pk=report.pk %}" class="see-more">Reporter {{ report.reporter.profile.profiles_name }}</a>
                                   </li>
                                </ul>
                                 {% empty %}
                                <div class="project-head"><h3>No Reports added</h3></div>
                                 {% endfor %}
                                <div class="button">
                                    <button><a href="{% url 'report-add' %}?task_id={{ task.pk }}">Add for this Task</a></button>
                                </div>
                        <!-- </form> -->
                     </div>
                </article>
        </main>
{% endblock %}

ConstructionProjectManagement/templates/tasks/tasks-edit.html
{% extends 'base.html' %}
{% load static %}
{% block content %}
        <main>
                <article class="top">
                    <div class="register-form form">
                       <h2 class="project-details">Edit Task</h2>
                       <form class="" method="POST" action="{% url 'task-edit' pk=task.pk %}">
                           {% csrf_token %}
                           {{ form }}
{#                            <div class="context">#}
{#                                <p class="content-p">Gazoprovod Europ Africakjkjhkjkhk jhhhhhhhhh </p>#}
{#                                <p class="author">Author: Ivan Ivanov Position: Technical manager</p>#}
{#                                <p class="author">Company: Stroitel AD Created at 22.2.2024 15:30</p>#}
{#                            </div>#}
                            <div class="button">
                                <button type="submit">Edit</button>
                            </div>
                       </form>
                    </div>
                </article>
        </main>
{% endblock %}

ConstructionProjectManagement/templates/tasks/tasks.html
{% extends 'base.html' %}
{% load static %}
{% block content %}
        <main>
                <article class="top">
                     <div class="register-form form">
                        <h2 class="project-details">Tasks</h2>
                         {% for task in task_list %}
                            <ul class="list">
                               <li type="none">
                                   <a href="{% url 'task-detail' pk=task.pk %}" class="see-more">Task {{ task.project }}</a>
                               </li>
                            </ul>
                         {% empty %}
                            <div class="project-head"><h3>No tasks added</h3></div>
                         {% endfor %}
                            <div class="button">
                               <button><a href="{% url 'task-create' %}">Add</a></button>
                            </div>
                     </div>
                </article>
        </main>
{% endblock %}