ConstructionProjectManagement/ConstructionProjectManagement/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [

    path('admin/', admin.site.urls),
    path('accounts/', include('accounts.urls')),
    path('', include('common.urls')),
    path('projects/', include('projects.urls')),

    path('builders/', include('builders.urls')),

    path('designers/', include('designers.urls')),
    path('supervisions/', include('supervisions.urls')),
    path('tasks/', include('tasks.urls')),
]

if settings.DEBUG:
    # urlpatterns += static(settings.STATIC_URL, document_root=settings.STATICFILES_DIRS[0])
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

ConstructionProjectManagement/supervisions/urls.py
from django.urls.conf import path, include

from supervisions import views

urlpatterns = [
    path('', views.SupervisionListView.as_view(), name='supervisions'),
    path('create/', views.SupervisionCreateView.as_view(), name='supervision-create'),
    path('<int:pk>/', include([
        path('details', views.SupervisionDetailView.as_view(), name='supervision-details'),
        path('edit/', views.SupervisionEditView.as_view(), name='supervision-edit'),
    ])),
]

ConstructionProjectManagement/tasks/urls.py
from django.urls.conf import path, include

from tasks import views

urlpatterns = [
    path('', views.TaskListView.as_view(), name='tasks'),
    path('create/', views.TaskCreateView.as_view(), name='task-create'),
    path('<int:pk>/', include([
        path('detail/', views.TaskDetailView.as_view(), name='task-detail'),
        path('edit/', views.TaskEditView.as_view(), name='task-edit'),
        path('delete/', views.TaskDeleteView.as_view(), name='task-delete'),
    ])),
    # path('reports/', views.ReportListView.as_view(), name='reports'),
    path('report-add/', views.ReportCreateView.as_view(), name='report-add'),
    path('report/<int:rep_pk>/', include([
        path('detail/', views.ReportDetailView.as_view(), name='report-detail'),
        path('edit/', views.ReportEditView.as_view(), name='report-edit'),
        path('delete/', views.ReportDeleteView.as_view(), name='report-delete'),
    ]))

]

ConstructionProjectManagement/supervisions/models.py
from django.db import models
from core.mixins import AbstractBaseMixin
from core.validators import SizeValidator

# Create your models here.


class Supervision(AbstractBaseMixin):
    document = models.FileField(
        validators=[
            SizeValidator(5),
        ],
        upload_to='supervision_documents',
    )
    project = models.ManyToManyField('projects.Project', related_name='supervisions')

ConstructionProjectManagement/supervisions/forms.py
from django import forms
from core.mixins import ReadOnlyFieldsMixin, ContractBaseForm
from supervisions.models import Supervision
from projects.models import Project


class SupervisionBaseForm(ContractBaseForm):
    project = forms.ModelMultipleChoiceField(
        queryset=Project.objects.all(),
        required=False,
        label="Connect to projects",
        widget=forms.CheckboxSelectMultiple()
    )

    class Meta(ContractBaseForm.Meta):
        model = Supervision
        fields = '__all__'


class SupervisionCreateForm(SupervisionBaseForm):
    ...


class SupervisionEditForm(SupervisionBaseForm):
    ...


class SupervisionDetailsForm(SupervisionBaseForm):
    ...


class SupervisionDeleteForm(SupervisionBaseForm, ReadOnlyFieldsMixin):
    class Meta(SupervisionBaseForm.Meta):
        model = Supervision
        exclude = ('budged', 'phone_number', 'email', 'document', 'project')

ConstructionProjectManagement/supervisions/views.py
from django.contrib.auth.mixins import LoginRequiredMixin, PermissionRequiredMixin
from django.urls.base import reverse
from django.views.generic.detail import DetailView
from django.views.generic.edit import CreateView, UpdateView
from django.views.generic.list import ListView

from supervisions.forms import SupervisionCreateForm, SupervisionEditForm
from supervisions.models import Supervision


# Create your views here.
class SupervisionListView(LoginRequiredMixin, ListView):
    model = Supervision
    template_name = 'supervision/supervisions.html'


class SupervisionCreateView(PermissionRequiredMixin, CreateView):
    permission_required = 'supervisions.add_supervision'
    model = Supervision
    template_name = 'supervision/supervision-add.html'
    form_class = SupervisionCreateForm

    def form_valid(self, form):
        return super().form_valid(form)

    def get_success_url(self) -> str:
        return reverse(
            'supervisions',
        )


class SupervisionDetailView(LoginRequiredMixin, DetailView):
    model = Supervision
    template_name = 'supervision/supervision-details.html'
    pk_url_kwarg = 'pk'

    def get_context_data(self, **kwargs):
        supervision = self.get_object()
        kwargs.update({'supervision': supervision})
        return super().get_context_data(**kwargs)


class SupervisionEditView(PermissionRequiredMixin, UpdateView):
    permission_required = 'supervisions.change_supervision'
    model = Supervision
    template_name = 'supervision/supervision-edit.html'
    pk_url_kwarg = 'pk'
    form_class = SupervisionEditForm

    def get_success_url(self) -> str:
        return reverse('supervision-details', kwargs={'pk': self.object.pk})

ConstructionProjectManagement/templates/supervision/supervision-add.html
{% extends 'base.html' %}
{% load static %}
{% block content %}
        <main>
            <article class="top">
                 <div class="register-form form">
                    <form class="" enctype="multipart/form-data" method="POST" action="{% url 'supervision-create' %}">
                        <h2 class="project-details">Add Supervision</h2>
                       {% csrf_token %}
                        {{ form }}
                        <div class="button">
                           <button type="submit">Add</button>
                        </div>
                    </form>
                 </div>
            </article>
        </main>
{% endblock %}

ConstructionProjectManagement/templates/supervision/supervision-details.html
{% extends 'base.html' %}
{% load static %}
{% block content %}
        <main>
            <article class="top">
                <div class="register-form form">
                   <form class="" method="GET" action="">
                       <h2 class="project-details">Supervision details</h2>
                       <h3 class="details-head">Company name:</h3>
                       <div class="context">{{ supervision.company_name }}</div>
                       <h3 class="project-head">Permit:</h3>
                       <div class="context">{{ supervision.permit }}</div>
                       <h3 class="project-head">Contract:</h3>
                       <div class="context">{{ supervision.contract }}</div>
                       <h3 class="project-head">Budget:</h3>
                       <div class="context">{{ supervision.budged }}euro</div>
                       <h3 class="project-head">Phone number:</h3>
                       <div class="context">+{{ supervision.phone_number }}</div>
                       <h3 class="project-head">Email:</h3>
                       <div class="context">{{ supervision.email}}</div>
                        <h3 class="project-head">Project:</h3>
                        <div class="context">{{ supervision.project.all|join:', '|default:'N/A'}}</div>
                   </form>
                   <div class="button">
                      <button><a href="{% url 'supervision-edit' pk=supervision.pk %}">Edit</a></button>
                   </div>
                </div>
            </article>
        </main>
{% endblock %}

ConstructionProjectManagement/templates/supervision/supervision-edit.html
{% extends 'base.html' %}
{% load static %}
{% block content %}
        <main>
                <article class="top">
                     <div class="register-form form">
                        <form class="" enctype="multipart/form-data" method="POST" action="{% url 'supervision-edit' pk=supervision.pk %}">
                            <h2 class="project-details">Edit Supervision</h2>
                            {% csrf_token %}
                            {{ form }}
                            <div class="button">
                               <button type="submit">Edit</button>
                            </div>
                        </form>
                     </div>
                </article>
        </main>
{% endblock %}

ConstructionProjectManagement/templates/supervision/supervisions.html
{% extends 'base.html' %}
{% load static %}
{% block content %}
       <main>
            <article class="top">
                 <div class="register-form form">
                    <h2 class="project-details">Supervisions</h2>
                     {% for supervision in supervision_list %}
                    <ul class="list">
                       <li>
                           <a href="{% url 'supervision-details' pk=supervision.pk %}" class="see-more">Supervision: {{ supervision.company_name}}</a>
                       </li>
                    </ul>
                     {% empty %}
                    <div class="project-head"><h3>No supervisions added</h3></div>
                     {% endfor %}
                    <div class="button">
                       <button><a href="{% url 'supervision-create' %}">Add</a></button>
                    </div>
                 </div>
            </article>
        </main>
{% endblock %}