ConstructionProjectManagement/ConstructionProjectManagement/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [

    path('admin/', admin.site.urls),
    path('accounts/', include('accounts.urls')),
    path('', include('common.urls')),
    path('projects/', include('projects.urls')),

    path('builders/', include('builders.urls')),

    path('designers/', include('designers.urls')),
    path('supervisions/', include('supervisions.urls')),
    path('tasks/', include('tasks.urls')),
]

if settings.DEBUG:
    # urlpatterns += static(settings.STATIC_URL, document_root=settings.STATICFILES_DIRS[0])
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

ConstructionProjectManagement/designers/urls.py
from django.urls.conf import path, include
from designers import views

urlpatterns = [
    path('', views.DesignerListView.as_view(), name='designers'),
    path('create/', views.DesignerCreateView.as_view(), name='designer-create'),
    path('<int:pk>/', include([
        path('details', views.DesignerDetailView.as_view(), name='designer-details'),
        path('edit/', views.DesignerEditView.as_view(), name='designer-edit'),
    ])),
]

ConstructionProjectManagement/tasks/urls.py
from django.urls.conf import path, include

from tasks import views

urlpatterns = [
    path('', views.TaskListView.as_view(), name='tasks'),
    path('create/', views.TaskCreateView.as_view(), name='task-create'),
    path('<int:pk>/', include([
        path('detail/', views.TaskDetailView.as_view(), name='task-detail'),
        path('edit/', views.TaskEditView.as_view(), name='task-edit'),
        path('delete/', views.TaskDeleteView.as_view(), name='task-delete'),
    ])),
    # path('reports/', views.ReportListView.as_view(), name='reports'),
    path('report-add/', views.ReportCreateView.as_view(), name='report-add'),
    path('report/<int:rep_pk>/', include([
        path('detail/', views.ReportDetailView.as_view(), name='report-detail'),
        path('edit/', views.ReportEditView.as_view(), name='report-edit'),
        path('delete/', views.ReportDeleteView.as_view(), name='report-delete'),
    ]))

]

ConstructionProjectManagement/designers/models.py
from django.db import models
from core.mixins import AbstractBaseMixin
from core.validators import SizeValidator

# Create your models here.


class Designer(AbstractBaseMixin):
    document = models.FileField(
        validators=[
            SizeValidator(5),
        ],
        upload_to='designer_documents',
    )
    project = models.ManyToManyField('projects.Project', related_name='designers')

ConstructionProjectManagement/designers/forms.py
from django import forms
from core.mixins import ReadOnlyFieldsMixin, ContractBaseForm
from designers.models import Designer
from projects.models import Project


class DesignerBaseForm(ContractBaseForm):
    project = forms.ModelMultipleChoiceField(
        queryset=Project.objects.all(),
        required=False,
        label="Connect to projects",
        widget=forms.CheckboxSelectMultiple()
    )

    class Meta(ContractBaseForm.Meta):
        model = Designer
        fields = '__all__'


class DesignerCreateForm(DesignerBaseForm):
    ...


class DesignerEditForm(DesignerBaseForm):
    ...


class DesignerDetailsForm(DesignerBaseForm):
    ...


class DesignerDeleteForm(DesignerBaseForm, ReadOnlyFieldsMixin):
    class Meta(DesignerBaseForm.Meta):
        model = Designer
        exclude = ('budged', 'phone_number', 'email', 'document', 'project')

ConstructionProjectManagement/designers/views.py
from django.contrib.auth.mixins import LoginRequiredMixin, PermissionRequiredMixin
from django.urls.base import reverse
from django.views.generic.detail import DetailView
from django.views.generic.edit import CreateView, UpdateView
from django.views.generic.list import ListView

from designers.forms import DesignerCreateForm, DesignerEditForm
from designers.models import Designer
# Create your views here.


class DesignerListView(LoginRequiredMixin, ListView):
    model = Designer
    template_name = 'designer/designers.html'


class DesignerCreateView(PermissionRequiredMixin, CreateView):
    permission_required = 'designers.add_designer'
    model = Designer
    template_name = 'designer/designer-add.html'
    form_class = DesignerCreateForm

    def form_valid(self, form):
        return super().form_valid(form)

    def get_success_url(self) -> str:
        return reverse(
            'designers',
        )


class DesignerDetailView(LoginRequiredMixin, DetailView):
    model = Designer
    template_name = 'designer/designer-details.html'
    pk_url_kwarg = 'pk'

    def get_context_data(self, **kwargs):
        designer = self.get_object()
        kwargs.update({'designer': designer})
        return super().get_context_data(**kwargs)


class DesignerEditView(PermissionRequiredMixin, UpdateView):
    permission_required = 'designers.change_designer'
    model = Designer
    template_name = 'designer/designer-edit.html'
    pk_url_kwarg = 'pk'
    form_class = DesignerEditForm

    def get_success_url(self) -> str:
        return reverse('designer-details', kwargs={'pk': self.object.pk})

ConstructionProjectManagement/templates/designer/designer-add.html
{% extends 'base.html' %}
{% load static %}
{% block content %}
        <main>
            <article class="top">
                 <div class="register-form form">
                    <form class="" enctype="multipart/form-data" method="POST" action="{% url 'designer-create' %}">
                        <h2 class="project-details">Add Designer</h2>
                        {% csrf_token %}
                        {{ form }}
                        <div class="button">
                           <button type="submit">Add</button>
                        </div>
                    </form>
                 </div>
            </article>
        </main>
{% endblock %}

ConstructionProjectManagement/templates/designer/designer-details.html
{% extends 'base.html' %}
{% load static %}
{% block content %}
        <main>
            <article class="top">
                <div class="register-form form">
                   <form class="" method="GET" action="">
                       <h2 class="project-details">Designer details</h2>
                       <h3 class="details-head">Company name:</h3>
                       <div class="context">{{ designer.company_name }}</div>
                       <h3 class="project-head">Permit:</h3>
                       <div class="context">{{ designer.permit }}</div>
                       <h3 class="project-head">Contract:</h3>
                       <div class="context">{{ designer.contract }}</div>
                       <h3 class="project-head">Budget:</h3>
                       <div class="context">{{ designer.budged }}euro</div>
                       <h3 class="project-head">Phone number:</h3>
                       <div class="context">+{{ designer.phone_number }}</div>
                       <h3 class="project-head">Email:</h3>
                       <div class="context">{{ designer.email}}</div>
                        <h3 class="project-head">Project:</h3>
                        <div class="context">{{ designer.project.all|join:', '|default:'N/A'}}</div>
                   </form>
                   <div class="button">
                      <button><a href="{% url 'designer-edit' pk=designer.pk %}">Edit</a></button>
                   </div>
                </div>
            </article>
        </main>
{% endblock %}

ConstructionProjectManagement/templates/designer/designer-edit.html
{% extends 'base.html' %}
{% load static %}
{% block content %}
        <main>
                <article class="top">
                     <div class="register-form form">
                        <form class="" enctype="multipart/form-data" method="POST" action="{% url 'designer-edit' pk=designer.pk %}">
                            <h2 class="project-details">Edit Designer</h2>
                            {% csrf_token %}
                            {{ form }}
                            <div class="button">
                               <button type="submit">Edit</button>
                            </div>
                        </form>
                     </div>
                </article>
        </main>
{% endblock %}

ConstructionProjectManagement/templates/designer/designers.html
{% extends 'base.html' %}
{% load static %}
{% block content %}

        <main>
                <article class="top">
                     <div class="register-form form">
                        <h2 class="project-details">Designers</h2>
                         {% for designer in designer_list %}
                        <ul class="list">
                           <li>
                               <a href="{% url 'designer-details' pk=designer.pk %}" class="see-more">Designer: {{ designer.company_name }}</a>
                           </li>
                        </ul>
                         {% empty %}
                        <div class="project-head"><h3>No designers added</h3></div>
                         {% endfor %}
                        <div class="button">
                           <button><a href="{% url 'designer-create' %}">Add</a></button>
                        </div>
                     </div>
                </article>
        </main>
{% endblock %}